### PR TITLE
V1.0

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
please ignore all in resources/

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1#-:-LRC3Xia4GIS9Dd38yUA:bgqnpl5)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @andyb3)

**Review by andyb3 — CHANGES_REQUESTED** [review]
Could you describe what has changed from the original `GATK3 Human Exome Pipeline v1.4` app? Is the code.sh just a subset of that, or has anything within it changed?

> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1#-:-LRCQZsMEJQrd1YXrNu7:bri6jk8)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @andyb3)

___
*[src/code.sh, line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1#-LRCOLb62mOLOABsjeXr:-LRCOLb62mOLOABsjeXs:b-kj92tr) ([raw file](https://github.com/moka-guys/dnanexus_gatk_preprocessing/blob/32d900bce5f21ebd04244178ec2ddfc75fd0939a/src/code.sh#L12)):*
> ```Shell
> # Fetch inputs
> #
> #mark-section "downloading inputs"
> ```

Why are the mark-section commands commented out? Can you remind me what these do?
___
*[src/code.sh, line 39 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1#-LRCRK4LEjBp6FSOxpK7:-LRCRK4LEjBp6FSOxpK8:babqvzb) ([raw file](https://github.com/moka-guys/dnanexus_gatk_preprocessing/blob/32d900bce5f21ebd04244178ec2ddfc75fd0939a/src/code.sh#L39)):*
> ```Shell
> #
> #mark-section "detecting reference genome"
> samtools view -H "$sorted_bam_path" | grep ^@SQ | cut -f1-3 | md5sum | cut -c1-32 >.genome-fingerprint.txt
> ```

I think some additional commenting throughout this file would be helpful, although I realise this is probably all lifted straight from the additonal app.

**Review by andyb3 — COMMENTED** [review]
Ignored files under resources

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1#-:-LRCSEhp7uWlMDby53tU:b-b7qfmn)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @andyb3)

**Review by aledj2 — COMMENTED** [review]
GATK.jar now bundled in app (not an input)
Haplotype caller inputs and options removed (bed file input,"padding", "extra_hc_options", "extra_gg_options" and "output_format" options)
Haplotype caller outputs removed ( 4 x VCF/VCF.tbi outputs)

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1#-:-LRM1ZG9BAypmbQA5q2b:b-722u4v)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @andyb3)

___
*[src/code.sh, line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1#-LRCOLb62mOLOABsjeXr:-LRM2VRC7y-o7ImaO9_W:b-qcdg3t) ([raw file](https://github.com/moka-guys/dnanexus_gatk_preprocessing/blob/32d900bce5f21ebd04244178ec2ddfc75fd0939a/src/code.sh#L12)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Why are the mark-section commands commented out? Can you remind me what these do?
</blockquote></details>

I think these just print something to standard out/ log and uses a file bundled in resources/usr/bin. When first started using Nexus these files were removed or had insufficient permission/execution properties which caused apps to fail so without any clear gain they were just commented out. 
___
*[src/code.sh, line 39 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1#-LRCRK4LEjBp6FSOxpK7:-LRM6WN-4L5PYbLU8Hrp:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_gatk_preprocessing/blob/32d900bce5f21ebd04244178ec2ddfc75fd0939a/src/code.sh#L39)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

I think some additional commenting throughout this file would be helpful, although I realise this is probably all lifted straight from the additonal app.
</blockquote></details>

Done.

**Review by andyb3 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/code.sh, line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/1#-LRCOLb62mOLOABsjeXr:-LRS20Q64WdTuFR6SGPe:b32w0x) ([raw file](https://github.com/moka-guys/dnanexus_gatk_preprocessing/blob/32d900bce5f21ebd04244178ec2ddfc75fd0939a/src/code.sh#L12)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I think these just print something to standard out/ log and uses a file bundled in resources/usr/bin. When first started using Nexus these files were removed or had insufficient permission/execution properties which caused apps to fail so without any clear gain they were just commented out. 
</blockquote></details>

OK

**Pull request merged**
