### PR TITLE
change to one thread to make deterministic. Allow each tool to be ski…

### PR DESCRIPTION
**Pull request by aledj2**
…pped individually

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/2)

### CODE REVIEW

**Review by andyb3 — COMMENTED** [review]
+@andyb3 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/2#-:-LkU8ZyW8xl45WuQNx5Y:bxccsfn)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @andyb3)

**Review by andyb3 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/2)* status: all files reviewed, 2 unresolved discussions (waiting on @aledj2)

___
*[src/code.sh, line 10 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/2#-LkU8vu0DFQMHJj4LsLL:-LkU8vu0DFQMHJj4LsLM:b-kou7s7) ([raw file](https://github.com/moka-guys/dnanexus_gatk_preprocessing/blob/ef5e2d04b30e6f005a0fe1ce0179117be0b5cdbf/src/code.sh#L10)):*
> ```Shell
> if [[ "$skip_markduplicates" == "true" ]] && [[ "$skip_BQSR" == "true" ]] && [[ "$skip_indelrealignment" == "true" ]]
> then
> exit
> ```

Minor thing but could this be indented?
___
*[src/code.sh, line 97 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/2#-LkU9BOT2i8TpFtON8Vi:-LkU9BOT2i8TpFtON8Vj:b-p906d5) ([raw file](https://github.com/moka-guys/dnanexus_gatk_preprocessing/blob/ef5e2d04b30e6f005a0fe1ce0179117be0b5cdbf/src/code.sh#L97)):*
> ```Shell
>   rm -f "$sorted_bam_path"
>   realign_input="deduplicated.bam"
> # if mark suplicates is skipped we need to set the inputs for the next tool to the files input to mark duplicates. This also requires an indexed BAM so need to create this index.
> ```

typo suplicates -> duplicates

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/2)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andyb3)

___
*[src/code.sh, line 97 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/2#-LkU9BOT2i8TpFtON8Vi:-LkUJLuX101nYiS0HdbB:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_gatk_preprocessing/blob/ef5e2d04b30e6f005a0fe1ce0179117be0b5cdbf/src/code.sh#L97)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

typo suplicates -> duplicates
</blockquote></details>

Done.
___
*[src/code.sh, line 148 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/2#-LkUJHp219x9HSmDMF5_:-LkUJHp3ClV-6t3fxGbM:baydar9) ([raw file](https://github.com/moka-guys/dnanexus_gatk_preprocessing/blob/ef5e2d04b30e6f005a0fe1ce0179117be0b5cdbf/src/code.sh#L148)):*
> ```Shell
> if [[ "$skip_markduplicates" != "true" ]]
> then
> mark-section "uploading mark duplicates QC"
> ```

FYI also indented this - not sure why didn't show up in the diff

**Review by andyb3 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_gatk_preprocessing/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
